# permissions for end users to view dtclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dtcluster-viewer-role
rules:
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtclusters/status
  verbs:
  - get
