# permissions for end users to view dtmodels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dtmodel-viewer-role
rules:
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtmodels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtmodels/status
  verbs:
  - get
