# permissions for end users to edit dtnodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dtnode-editor-role
rules:
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtnodes/status
  verbs:
  - get
