# permissions for end users to view machinegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinegroup-viewer-role
rules:
- apiGroups:
  - apps.dtwave.com
  resources:
  - machinegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.dtwave.com
  resources:
  - machinegroups/status
  verbs:
  - get
