# permissions for end users to edit machinegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: machinegroup-editor-role
rules:
- apiGroups:
  - apps.dtwave.com
  resources:
  - machinegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dtwave.com
  resources:
  - machinegroups/status
  verbs:
  - get
