
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtclusters/finalizers
  verbs:
  - update
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtmachines/finalizers
  verbs:
  - update
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtmodels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtmodels/finalizers
  verbs:
  - update
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtmodels/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtnodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtnodes/finalizers
  verbs:
  - update
- apiGroups:
  - apps.dtwave.com
  resources:
  - dtnodes/status
  verbs:
  - get
  - patch
  - update
