apiVersion: apps.dtwave.com/v1
kind: Machine
metadata:
  name: machine-sample1
spec:
  type: clone
  user: deploy
  dtnode: "dtnode-sample"
  password: deploy@1298
  cpu: "2"
  memory: "1"
  disk: "100"

