apiVersion: apps.dtwave.com/v1
kind: DtNode
metadata:
  name: dtnode-dtwave-node2
spec:
  node: node2
  dtcluster:
    dtcluster-esxi: unknown
    dtcluster-pve: unknown
    dtcluster-aliyun: unknown
  provider: dtwave
  desc: "测试dtnode"
